STATES = [
    ('Abuja', 'Abuja'),
    ('Nasarawa', 'Nasarawa'),
    ('Nasarawa', 'Nasarawa'),
    ('Katsina', 'Katsina'),
    ('Kano', 'Kano'),
    ('Kaduna', 'Kaduna'),
    ('Kogi', 'Kogi'),
    ('Kebbi', 'Kebbi'),
    ('Adamawa', 'Adamawa'),
    ('Abia', 'Abia'),
    ('Akwa Ibon', 'Akwa Ibon'),
    ('Anamambra', 'Anamambra'),
    ('Bauchi', 'Bauchi'),
    ('Niger', 'Niger'),
    ('Ibonyi', 'Ibonyi'),
    ('Logos', 'Logos'),
    ('Beyelsa', 'Beyelsa'),
    ('Benue', 'Benue'),
    ('Borno', 'Borno'),
    ('Cross River', 'Cross River'),
    ('Delta', 'Delta'),
    ('Ebonyi', 'Ebonyi'),
    ('Osun', 'Osun'),
    ('Oyo', 'Oyo'),
    ('Ibadan', 'Ibadan'),
    ('Lokoja', 'Lokoja'),
    ('Kwara', 'Kwara'),
    ('Illorin', 'Illorin'),
    ('Sokoto', 'Sokoto'),
    ('Zamfara', 'Zamfara'),
    ('Taraba', 'Taraba'),
    ('Yobe', 'Yobe'),
    ('Platue', 'Platue'),
]

GENDER_CHOICES = [
        ('Male', 'Male'),
        ('Female', 'Female'),
]