# Generated by Django 3.2.9 on 2021-12-22 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20211222_1419'),
        ('errors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailerror',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='emailerror',
            name='domail',
            field=models.CharField(default='', max_length=65),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailerror',
            name='errorType',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailerror',
            name='html_path',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailerror',
            name='protocol',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailerror',
            name='reciever',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.account', verbose_name='reciever'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailerror',
            name='subject',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
