# Generated by Django 3.2.9 on 2021-12-23 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('errors', '0002_auto_20211222_1501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailerror',
            old_name='domail',
            new_name='domain',
        ),
    ]
