# Generated by Django 3.2.9 on 2021-12-19 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_account_accountnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('naration', models.TextField(help_text='Naration of transfer')),
                ('AccountNumber', models.CharField(blank=True, max_length=150)),
                ('WeebeeAddress', models.CharField(blank=True, max_length=150)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='accounts.account')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('transtype', models.IntegerField(choices=[(0, 'Deposit'), (1, 'Credit')], null=True, verbose_name='Transaction Type')),
                ('status', models.IntegerField(choices=[(0, 'Initiated'), (1, 'Declined'), (2, 'Aborted'), (3, 'Successful')])),
                ('previous_balance', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('balanceAfterTransaction', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reciever', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reciever', to='accounts.account')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='accounts.account')),
            ],
        ),
    ]
