# Generated by Django 3.2.7 on 2021-11-27 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_weebeeaddress'),
        ('transaction', '0002_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='reciever',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reciever', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='accounts.account'),
        ),
    ]
