# Generated by Django 3.2.9 on 2021-12-23 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_auto_20211223_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='naration',
            field=models.TextField(default='', help_text='Naration of transfer'),
            preserve_default=False,
        ),
    ]
