# Generated by Django 3.2.7 on 2021-11-27 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_alter_transaction_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='balance',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='transaction',
            name='transtype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transaction.transactiontype'),
        ),
    ]
