# Generated by Django 3.2.9 on 2021-12-23 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_transaction_naration'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebitRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='a1', to='transaction.transaction')),
                ('debit', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='b2', to='transaction.transaction')),
            ],
        ),
    ]
