# Generated by Django 3.2.7 on 2021-11-27 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_auto_20211127_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transtype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transaction.transactiontype', verbose_name='Transaction Type'),
        ),
    ]
