# Generated by Django 3.2.7 on 2021-11-28 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_alter_transaction_transtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='balanceAfterTransaction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
    ]
