# Generated by Django 3.2.9 on 2021-12-07 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0009_alter_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='previous_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.IntegerField(choices=[(0, 'Initiated'), (1, 'Declined'), (2, 'Aborted'), (3, 'Successful')], default=0),
            preserve_default=False,
        ),
    ]
