# Generated by Django 3.2.9 on 2021-12-08 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0010_auto_20211207_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transtype',
            field=models.IntegerField(choices=[(0, 'Deposit'), (1, 'Credit')], null=True, verbose_name='Transaction Type'),
        ),
        migrations.DeleteModel(
            name='TransactionType',
        ),
    ]
