# Generated by Django 3.2.9 on 2021-12-09 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0013_transfer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='reciever',
        ),
        migrations.AddField(
            model_name='transfer',
            name='AccountNumber',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='transfer',
            name='WeebeeAddress',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='transfer',
            name='naration',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
