# Generated by Django 3.2.9 on 2021-12-19 19:43

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('maximunWidrawal', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firstName', models.CharField(default='', max_length=50, verbose_name='First Name')),
                ('lastName', models.CharField(default='', max_length=50, verbose_name='Last Name')),
                ('middleName', models.CharField(max_length=50, null=True, verbose_name='Middle Name')),
                ('dateOfBirth', models.DateField(verbose_name='Date of birth')),
                ('phoneNumber', models.CharField(default='', max_length=20)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('stateOfOrigin', models.CharField(choices=[('Abuja', 'Abuja'), ('Nasarawa', 'Nasarawa'), ('Nasarawa', 'Nasarawa'), ('Katsina', 'Katsina'), ('Kano', 'Kano'), ('Kaduna', 'Kaduna'), ('Kogi', 'Kogi'), ('Kebbi', 'Kebbi'), ('Adamawa', 'Adamawa'), ('Abia', 'Abia'), ('Akwa Ibon', 'Akwa Ibon'), ('Anamambra', 'Anamambra'), ('Bauchi', 'Bauchi'), ('Niger', 'Niger'), ('Ibonyi', 'Ibonyi'), ('Logos', 'Logos'), ('Beyelsa', 'Beyelsa'), ('Benue', 'Benue'), ('Borno', 'Borno'), ('Cross River', 'Cross River'), ('Delta', 'Delta'), ('Ebonyi', 'Ebonyi'), ('Osun', 'Osun'), ('Oyo', 'Oyo'), ('Ibadan', 'Ibadan'), ('Lokoja', 'Lokoja'), ('Kwara', 'Kwara'), ('Illorin', 'Illorin'), ('Sokoto', 'Sokoto'), ('Zamfara', 'Zamfara'), ('Taraba', 'Taraba'), ('Yobe', 'Yobe'), ('Platue', 'Platue')], default='', max_length=20, verbose_name='State of origin')),
                ('idCardNumber', models.CharField(max_length=20, verbose_name='Identity card')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=0, max_length=20)),
                ('dateJoined', models.DateTimeField(auto_now=True, verbose_name='date joined')),
                ('address', models.TextField(default='')),
                ('state', models.CharField(choices=[('Abuja', 'Abuja'), ('Nasarawa', 'Nasarawa'), ('Nasarawa', 'Nasarawa'), ('Katsina', 'Katsina'), ('Kano', 'Kano'), ('Kaduna', 'Kaduna'), ('Kogi', 'Kogi'), ('Kebbi', 'Kebbi'), ('Adamawa', 'Adamawa'), ('Abia', 'Abia'), ('Akwa Ibon', 'Akwa Ibon'), ('Anamambra', 'Anamambra'), ('Bauchi', 'Bauchi'), ('Niger', 'Niger'), ('Ibonyi', 'Ibonyi'), ('Logos', 'Logos'), ('Beyelsa', 'Beyelsa'), ('Benue', 'Benue'), ('Borno', 'Borno'), ('Cross River', 'Cross River'), ('Delta', 'Delta'), ('Ebonyi', 'Ebonyi'), ('Osun', 'Osun'), ('Oyo', 'Oyo'), ('Ibadan', 'Ibadan'), ('Lokoja', 'Lokoja'), ('Kwara', 'Kwara'), ('Illorin', 'Illorin'), ('Sokoto', 'Sokoto'), ('Zamfara', 'Zamfara'), ('Taraba', 'Taraba'), ('Yobe', 'Yobe'), ('Platue', 'Platue')], default='', max_length=20)),
                ('postalCode', models.IntegerField(verbose_name='postal code')),
                ('city', models.CharField(max_length=256)),
                ('country', django_countries.fields.CountryField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('weebeeAddress', models.CharField(blank=True, default='@weebee.com', max_length=200, unique=True, verbose_name='Weebee Address')),
                ('accountNumber', models.CharField(blank=True, default=7832317599, max_length=15, unique=True, verbose_name='Account Number')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('accountActivated', models.BooleanField(default=True, verbose_name='Account activated')),
                ('allowSMS', models.BooleanField(default=True, verbose_name='allowed sms?')),
                ('initialDepositDate', models.DateTimeField(null=True, verbose_name='Initial deposit')),
                ('lastUpdate', models.DateTimeField(null=True, verbose_name='last updated')),
                ('accountType', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.accounttype', verbose_name='Account type')),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='accounts.customer')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
