# Generated by Django 3.2.9 on 2021-12-19 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='accountNumber',
            field=models.CharField(blank=True, default=5723650564, max_length=15, unique=True, verbose_name='Account Number'),
        ),
    ]
