# Generated by Django 3.2.7 on 2021-11-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20211127_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='date_joined',
            new_name='date_created',
        ),
        migrations.AddField(
            model_name='user',
            name='dateOfBirth',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='accounttype',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
