# Generated by Django 3.2.9 on 2021-12-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20211219_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='accountNumber',
            field=models.CharField(blank=True, default=2467727963, max_length=15, unique=True, verbose_name='Account Number'),
        ),
    ]
