# Generated by Django 3.2.7 on 2021-11-27 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20211127_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='accountType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.accounttype'),
        ),
    ]
