# Generated by Django 3.2.7 on 2021-11-27 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_account_accounttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='accountNumber',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
