# Generated by Django 3.2.9 on 2021-12-22 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_account_accountnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='accountNumber',
            field=models.CharField(blank=True, max_length=15, unique=True, verbose_name='Account Number'),
        ),
        migrations.AlterField(
            model_name='account',
            name='initialDepositDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Initial deposit'),
        ),
        migrations.AlterField(
            model_name='account',
            name='lastUpdate',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='last updated'),
        ),
        migrations.AlterField(
            model_name='account',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='accounts.customer', unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='middleName',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Middle Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phoneNumber',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='postalCode',
            field=models.DecimalField(decimal_places=0, max_digits=9, verbose_name='postal code'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Abuja', 'Abuja'), ('Nasarawa', 'Nasarawa'), ('Nasarawa', 'Nasarawa'), ('Katsina', 'Katsina'), ('Kano', 'Kano'), ('Kaduna', 'Kaduna'), ('Kogi', 'Kogi'), ('Kebbi', 'Kebbi'), ('Adamawa', 'Adamawa'), ('Abia', 'Abia'), ('Akwa Ibon', 'Akwa Ibon'), ('Anamambra', 'Anamambra'), ('Bauchi', 'Bauchi'), ('Niger', 'Niger'), ('Ibonyi', 'Ibonyi'), ('Logos', 'Logos'), ('Beyelsa', 'Beyelsa'), ('Benue', 'Benue'), ('Borno', 'Borno'), ('Cross River', 'Cross River'), ('Delta', 'Delta'), ('Ebonyi', 'Ebonyi'), ('Osun', 'Osun'), ('Oyo', 'Oyo'), ('Ibadan', 'Ibadan'), ('Lokoja', 'Lokoja'), ('Kwara', 'Kwara'), ('Illorin', 'Illorin'), ('Sokoto', 'Sokoto'), ('Zamfara', 'Zamfara'), ('Taraba', 'Taraba'), ('Yobe', 'Yobe'), ('Platue', 'Platue')], default=7, max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='stateOfOrigin',
            field=models.CharField(choices=[('Abuja', 'Abuja'), ('Nasarawa', 'Nasarawa'), ('Nasarawa', 'Nasarawa'), ('Katsina', 'Katsina'), ('Kano', 'Kano'), ('Kaduna', 'Kaduna'), ('Kogi', 'Kogi'), ('Kebbi', 'Kebbi'), ('Adamawa', 'Adamawa'), ('Abia', 'Abia'), ('Akwa Ibon', 'Akwa Ibon'), ('Anamambra', 'Anamambra'), ('Bauchi', 'Bauchi'), ('Niger', 'Niger'), ('Ibonyi', 'Ibonyi'), ('Logos', 'Logos'), ('Beyelsa', 'Beyelsa'), ('Benue', 'Benue'), ('Borno', 'Borno'), ('Cross River', 'Cross River'), ('Delta', 'Delta'), ('Ebonyi', 'Ebonyi'), ('Osun', 'Osun'), ('Oyo', 'Oyo'), ('Ibadan', 'Ibadan'), ('Lokoja', 'Lokoja'), ('Kwara', 'Kwara'), ('Illorin', 'Illorin'), ('Sokoto', 'Sokoto'), ('Zamfara', 'Zamfara'), ('Taraba', 'Taraba'), ('Yobe', 'Yobe'), ('Platue', 'Platue')], max_length=20, verbose_name='State of origin'),
        ),
    ]
