# Generated by Django 3.2.7 on 2021-11-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20211127_1622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone_number',
            new_name='phoneNumber',
        ),
        migrations.AlterField(
            model_name='user',
            name='firstName',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastName',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='middleName',
            field=models.CharField(default='', max_length=50),
        ),
    ]
