# Generated by Django 3.2.7 on 2021-11-27 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_customer_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_to', models.EmailField(max_length=254, null=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Abuja', 'Abuja'), ('Nasarawa', 'Nasarawa'), ('Nasarawa', 'Nasarawa'), ('Katsina', 'Katsina'), ('Kano', 'Kano'), ('Kaduna', 'Kaduna'), ('Kogi', 'Kogi'), ('Kebbi', 'Kebbi'), ('Adamawa', 'Adamawa'), ('Abia', 'Abia'), ('Akwa Ibon', 'Akwa Ibon'), ('Anamambra', 'Anamambra'), ('Bauchi', 'Bauchi'), ('Niger', 'Niger'), ('Ibonyi', 'Ibonyi'), ('Logos', 'Logos'), ('Beyelsa', 'Beyelsa'), ('Benue', 'Benue'), ('Borno', 'Borno'), ('Cross River', 'Cross River'), ('Delta', 'Delta'), ('Ebonyi', 'Ebonyi'), ('Osun', 'Osun'), ('Oyo', 'Oyo'), ('Ibadan', 'Ibadan'), ('Lokoja', 'Lokoja'), ('Kwara', 'Kwara'), ('Illorin', 'Illorin'), ('Sokoto', 'Sokoto'), ('Zamfara', 'Zamfara'), ('Taraba', 'Taraba'), ('Yobe', 'Yobe'), ('Platue', 'Platue')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='stateOfOrigin',
            field=models.CharField(choices=[('Abuja', 'Abuja'), ('Nasarawa', 'Nasarawa'), ('Nasarawa', 'Nasarawa'), ('Katsina', 'Katsina'), ('Kano', 'Kano'), ('Kaduna', 'Kaduna'), ('Kogi', 'Kogi'), ('Kebbi', 'Kebbi'), ('Adamawa', 'Adamawa'), ('Abia', 'Abia'), ('Akwa Ibon', 'Akwa Ibon'), ('Anamambra', 'Anamambra'), ('Bauchi', 'Bauchi'), ('Niger', 'Niger'), ('Ibonyi', 'Ibonyi'), ('Logos', 'Logos'), ('Beyelsa', 'Beyelsa'), ('Benue', 'Benue'), ('Borno', 'Borno'), ('Cross River', 'Cross River'), ('Delta', 'Delta'), ('Ebonyi', 'Ebonyi'), ('Osun', 'Osun'), ('Oyo', 'Oyo'), ('Ibadan', 'Ibadan'), ('Lokoja', 'Lokoja'), ('Kwara', 'Kwara'), ('Illorin', 'Illorin'), ('Sokoto', 'Sokoto'), ('Zamfara', 'Zamfara'), ('Taraba', 'Taraba'), ('Yobe', 'Yobe'), ('Platue', 'Platue')], default='', max_length=20),
        ),
    ]
