# Generated by Django 3.2.7 on 2021-11-27 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20211127_1953'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MailError',
        ),
    ]
