# Generated by Django 3.2.7 on 2021-11-28 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_delete_mailerror'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='accountNumber',
            field=models.CharField(blank=True, default='009185833062', max_length=15),
        ),
        migrations.AlterField(
            model_name='account',
            name='weebeeAddress',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Weebee Address'),
        ),
    ]
