# Generated by Django 3.2.9 on 2021-12-07 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_account_accountnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='accountdisabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='allowSMS',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='accountNumber',
            field=models.PositiveIntegerField(blank=True, default='001649627709', unique=True, verbose_name='Account Number'),
        ),
        migrations.AlterField(
            model_name='account',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='accounts.customer'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='idCardNumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='streetAddress',
            field=models.TextField(),
        ),
    ]
