# Generated by Django 3.2.9 on 2021-12-07 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20211207_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='initialDepositDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='lastUpdate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='accountNumber',
            field=models.PositiveIntegerField(blank=True, default='009159137795', unique=True, verbose_name='Account Number'),
        ),
    ]
