# Generated by Django 3.2.9 on 2021-12-07 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20211207_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='accountNumber',
            field=models.PositiveIntegerField(blank=True, default='004363960696', unique=True, verbose_name='Account Number'),
        ),
    ]
