# Generated by Django 3.2.9 on 2021-12-08 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_account_accountnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='streetAddress',
        ),
        migrations.AlterField(
            model_name='account',
            name='accountNumber',
            field=models.PositiveIntegerField(blank=True, unique=True, verbose_name='Account Number'),
        ),
        migrations.AlterField(
            model_name='account',
            name='accountType',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.accounttype', verbose_name='account type'),
        ),
        migrations.AlterField(
            model_name='account',
            name='accountdisabled',
            field=models.BooleanField(default=False, verbose_name='account disabled?'),
        ),
        migrations.AlterField(
            model_name='account',
            name='allowSMS',
            field=models.BooleanField(default=True, verbose_name='allowed sms?'),
        ),
        migrations.AlterField(
            model_name='account',
            name='initialDepositDate',
            field=models.DateTimeField(null=True, verbose_name='Initail deposit at'),
        ),
        migrations.AlterField(
            model_name='account',
            name='lastUpdate',
            field=models.DateTimeField(null=True, verbose_name='last updated'),
        ),
        migrations.AlterField(
            model_name='account',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='accounts.customer'),
        ),
        migrations.AlterField(
            model_name='account',
            name='weebeeAddress',
            field=models.CharField(blank=True, default='@weebee.com', max_length=200, verbose_name='Weebee Address'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='dateJoined',
            field=models.DateTimeField(auto_now=True, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='dateOfBirth',
            field=models.DateField(verbose_name='Date of birth'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='firstName',
            field=models.CharField(default='', max_length=50, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='idCardNumber',
            field=models.IntegerField(verbose_name='Identity card'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='lastName',
            field=models.CharField(default='', max_length=50, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='middleName',
            field=models.CharField(max_length=50, null=True, verbose_name='Middle Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phoneNumber',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='postalCode',
            field=models.IntegerField(verbose_name='postal code'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='stateOfOrigin',
            field=models.CharField(choices=[('Abuja', 'Abuja'), ('Nasarawa', 'Nasarawa'), ('Nasarawa', 'Nasarawa'), ('Katsina', 'Katsina'), ('Kano', 'Kano'), ('Kaduna', 'Kaduna'), ('Kogi', 'Kogi'), ('Kebbi', 'Kebbi'), ('Adamawa', 'Adamawa'), ('Abia', 'Abia'), ('Akwa Ibon', 'Akwa Ibon'), ('Anamambra', 'Anamambra'), ('Bauchi', 'Bauchi'), ('Niger', 'Niger'), ('Ibonyi', 'Ibonyi'), ('Logos', 'Logos'), ('Beyelsa', 'Beyelsa'), ('Benue', 'Benue'), ('Borno', 'Borno'), ('Cross River', 'Cross River'), ('Delta', 'Delta'), ('Ebonyi', 'Ebonyi'), ('Osun', 'Osun'), ('Oyo', 'Oyo'), ('Ibadan', 'Ibadan'), ('Lokoja', 'Lokoja'), ('Kwara', 'Kwara'), ('Illorin', 'Illorin'), ('Sokoto', 'Sokoto'), ('Zamfara', 'Zamfara'), ('Taraba', 'Taraba'), ('Yobe', 'Yobe'), ('Platue', 'Platue')], default='', max_length=20, verbose_name='State of origin'),
        ),
    ]
