# Generated by Django 3.2.9 on 2021-12-08 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20211208_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='accountNumber',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Account Number'),
        ),
    ]
