# Generated by Django 3.2.9 on 2021-12-09 15:47

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_account_accountnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='account',
            old_name='accountdisabled',
            new_name='accountActivated',
        ),
        migrations.AlterField(
            model_name='account',
            name='accountNumber',
            field=models.CharField(blank=True, default=8494113686, max_length=15, unique=True, verbose_name='Account Number'),
        ),
        migrations.AlterField(
            model_name='account',
            name='accountType',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.accounttype', verbose_name='Account type'),
        ),
        migrations.AlterField(
            model_name='account',
            name='initialDepositDate',
            field=models.DateTimeField(null=True, verbose_name='Initial deposit'),
        ),
        migrations.AlterField(
            model_name='account',
            name='weebeeAddress',
            field=models.CharField(blank=True, default='@weebee.com', max_length=200, unique=True, verbose_name='Weebee Address'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='customer',
            name='idCardNumber',
            field=models.CharField(max_length=20, verbose_name='Identity card'),
        ),
    ]
