# Generated by Django 3.2.9 on 2021-12-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20211209_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='accountActivated',
            field=models.BooleanField(default=True, verbose_name='Account activated'),
        ),
        migrations.AlterField(
            model_name='account',
            name='accountNumber',
            field=models.CharField(blank=True, default=3873507796, max_length=15, unique=True, verbose_name='Account Number'),
        ),
    ]
