# Generated by Django 3.2.9 on 2021-12-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20211209_1554'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Credit',
        ),
        migrations.DeleteModel(
            name='Deposit',
        ),
        migrations.AlterField(
            model_name='account',
            name='accountNumber',
            field=models.CharField(blank=True, default=8274021447, max_length=15, unique=True, verbose_name='Account Number'),
        ),
    ]
