# Generated by Django 3.2.9 on 2021-12-09 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20211209_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='accountNumber',
            field=models.CharField(blank=True, default=519351543, max_length=15, unique=True, verbose_name='Account Number'),
        ),
    ]
